# Use the official Node.js image
FROM node:latest

# Install pnpm globally
RUN npm install -g pnpm

# docker build --tag custom-node .

# go to your target dir
# docker run -it -v .:/project custom-node sh